library(ggplot2)
setwd("~/Documents/UCDavis/dib/MMETSP/git/MMETSP/")
annotation_stats<-read.csv("assembly_evaluation_data/annotation_stats.csv")
total_annotation_names<-read.csv("assembly_evaluation_data/collapse_names",sep="\t",header=TRUE)
transrate_reference<-read.csv("assembly_evaluation_data/transrate_reference_trinity2.2.0_v_ncgr.nt.csv")
nseqs<-transrate_reference[,c(44,2)]
head(annotation_stats)
colnames(annotation_stats)<-c("SampleName","total_annotated_contigs","unique_annotations","annotations_w_false_crbb","total_OrthoDB","unique_OrthoDB","false_crbb_OrthoDB","total_Pfam","unique_Pfam","false_crbb_Pfam","total_Rfam","unique_Rfam","false_crbb_Rfam")
annotation_stats_merge1<-merge(nseqs,total_annotation_names,by="SampleName",all.x=TRUE)
annotation_stats_merge2<-merge(annotation_stats_merge1,annotation_stats,by="SampleName",all.x=TRUE)
head(annotation_stats_merge2)
write.csv(annotation_stats_merge2,"assembly_evaluation_data/merged_annotation_stats.csv")

annotations<-annotation_stats_merge2
rownames(annotations)<-annotations$SampleName
annotations<-annotations[,2:16]
annotations_num<-as.matrix(annotations)
head(annotations_num)
hist(annotations_num[,1])
