#!/bin/bash
#PBS -l walltime=5:00:00:00,nodes=1:ppn=64
#PBS -l mem=300GB
#PBS -j oe
#PBS -A ged
#PBS -M ljcohen@msu.edu
#PBS -m ae
#PBS -W umask=027

cd ${PBS_O_WORKDIR}

python /mnt/home/ljcohen/bin/OrthoFinder-master/orthofinder.py -b /mnt/scratch/ljcohen/pep/Results_Jun25/WorkingDirectory/ -t 64

qstat -f ${PBS_JOBID}
cat ${PBS_NODEFILE} # Output Contents of the PBS NODEFILE
env | grep PBS # Print out values of the current jobs PBS environment variables
